# -*- coding: utf-8 -*-
"""mail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WxlViIVSwPS9JbWJBoL64mYnrOd5JCAC
"""

import smtplib, ssl

port = 465 #For SSL
smtp_server ="smtp.gmail.com"
sender_email="anuragp0010@gmail.com"    #Sender's Mail Address
receiver_email="1706208@kiit.ac.in"      #Receiver's Mail Address
password="The_berozgar"
message="""    Subject: Jenkins Report
    
    Testing Failed"""
    
context=ssl.create_default_context()
with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(sender_email, receiver_email, message)